# Cloudflare Pages configuration

[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[build.environment]
  VITE_BASE_PATH = "/"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Environment variables for production
[env.production]
  VITE_API_URL = "https://api.tapbattle.com"
  VITE_TELEGRAM_BOT_USERNAME = "TapBattleBot"

# Environment variables for preview/staging
[env.preview]
  VITE_API_URL = "https://api-staging.tapbattle.com"
  VITE_TELEGRAM_BOT_USERNAME = "TapBattleDevBot"
